font_family FiraCode Nerd Font
font_size 11.0
background_opacity 0.7
confirm_os_window_close 0
cursor_shape beam
cursor_beam_thickness 1.5
cursor_blink_interval 0
cursor_trail 1
cursor_trail_decay 0.05 0.2
mouse_hide_wait -1
hide_window_decorations yes
window_padding_width 12
